# Generated by Django 5.1.7 on 2025-06-13 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('num_pixels', models.CharField(blank=True, max_length=50, null=True)),
                ('aperture', models.CharField(blank=True, max_length=20, null=True)),
                ('MEFL', models.CharField(blank=True, max_length=20, null=True)),
                ('focus', models.CharField(blank=True, max_length=255, null=True)),
                ('zoom', models.CharField(blank=True, max_length=20, null=True)),
                ('placement', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Media_Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_type', models.CharField(max_length=50)),
                ('format_extension', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('flash', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(max_length=255)),
                ('display_width_px', models.PositiveIntegerField(blank=True, null=True)),
                ('display_height_px', models.PositiveIntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBaseApp.brand')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBaseApp.camera')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBaseApp.device')),
            ],
            options={
                'unique_together': {('device', 'camera')},
            },
        ),
        migrations.AddField(
            model_name='device',
            name='cameras',
            field=models.ManyToManyField(related_name='devices', through='DataBaseApp.DeviceCamera', to='DataBaseApp.camera'),
        ),
        migrations.CreateModel(
            name='Camera_Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBaseApp.camera')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBaseApp.feature')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='features',
            field=models.ManyToManyField(through='DataBaseApp.Camera_Features', to='DataBaseApp.feature'),
        ),
        migrations.CreateModel(
            name='Camera_Medias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBaseApp.camera')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBaseApp.media_format')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='media_formats',
            field=models.ManyToManyField(through='DataBaseApp.Camera_Medias', to='DataBaseApp.media_format'),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=100)),
                ('sensor_format', models.CharField(blank=True, max_length=100, null=True)),
                ('pixel_size', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('sensor_type', 'sensor_format', 'pixel_size')},
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBaseApp.sensor'),
        ),
    ]
